project:
  type: website

website:
  title: "Search Highlight Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tabsets.qmd
        text: Tabsets
      - href: pandas.qmd
        text: Pandas
      - href: visualization.qmd
        text: Visualization
      - href: modeling.qmd
        text: Modeling
  repo-url: https://github.com/cderv/quarto-search-highlight-demo
  repo-actions: [issue]
  search: true

format:
  html:
    theme: cosmo
